package buku.entities;

// Generated Mar 22, 2014 2:39:02 AM by Hibernate Tools 4.0.0

/**
 * BillSplitees generated by hbm2java
 */
public class BillSplitees implements java.io.Serializable {

	private Integer id;
	private User user;
	private Currency currency;
	private Double amountToPay;
	private Integer billId;

	public BillSplitees() {
	}

	public BillSplitees(User user) {
		this.user = user;
	}

	public BillSplitees(User user, Currency currency, Double amountToPay,
			Integer billId) {
		this.user = user;
		this.currency = currency;
		this.amountToPay = amountToPay;
		this.billId = billId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Currency getCurrency() {
		return this.currency;
	}

	public void setCurrency(Currency currency) {
		this.currency = currency;
	}

	public Double getAmountToPay() {
		return this.amountToPay;
	}

	public void setAmountToPay(Double amountToPay) {
		this.amountToPay = amountToPay;
	}

	public Integer getBillId() {
		return this.billId;
	}

	public void setBillId(Integer billId) {
		this.billId = billId;
	}

}
