package buku.entities;

// Generated Mar 22, 2014 2:39:02 AM by Hibernate Tools 4.0.0

/**
 * CurrencyCode generated by hbm2java
 */
public class CurrencyCode implements java.io.Serializable {

	private Integer id;
	private String countryCurrencyCode;

	public CurrencyCode() {
	}

	public CurrencyCode(String countryCurrencyCode) {
		this.countryCurrencyCode = countryCurrencyCode;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCountryCurrencyCode() {
		return this.countryCurrencyCode;
	}

	public void setCountryCurrencyCode(String countryCurrencyCode) {
		this.countryCurrencyCode = countryCurrencyCode;
	}

}
