package buku.entities;

// Generated Mar 22, 2014 2:39:02 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * ItemType generated by hbm2java
 */
public class ItemType implements java.io.Serializable {

	private Integer id;
	private String itemTypeName;
	private String description;
	private Set loanItems = new HashSet(0);

	public ItemType() {
	}

	public ItemType(String itemTypeName, String description, Set loanItems) {
		this.itemTypeName = itemTypeName;
		this.description = description;
		this.loanItems = loanItems;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getItemTypeName() {
		return this.itemTypeName;
	}

	public void setItemTypeName(String itemTypeName) {
		this.itemTypeName = itemTypeName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getLoanItems() {
		return this.loanItems;
	}

	public void setLoanItems(Set loanItems) {
		this.loanItems = loanItems;
	}

}
