package buku.entities;

// Generated Mar 22, 2014 2:39:02 AM by Hibernate Tools 4.0.0

/**
 * LoanMoney generated by hbm2java
 */
public class LoanMoney implements java.io.Serializable {

	private Integer id;
	private User userByLoanUserId;
	private User userByOwnerUserId;
	private Double totalLoanAmount;

	public LoanMoney() {
	}

	public LoanMoney(User userByLoanUserId, User userByOwnerUserId,
			Double totalLoanAmount) {
		this.userByLoanUserId = userByLoanUserId;
		this.userByOwnerUserId = userByOwnerUserId;
		this.totalLoanAmount = totalLoanAmount;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUserByLoanUserId() {
		return this.userByLoanUserId;
	}

	public void setUserByLoanUserId(User userByLoanUserId) {
		this.userByLoanUserId = userByLoanUserId;
	}

	public User getUserByOwnerUserId() {
		return this.userByOwnerUserId;
	}

	public void setUserByOwnerUserId(User userByOwnerUserId) {
		this.userByOwnerUserId = userByOwnerUserId;
	}

	public Double getTotalLoanAmount() {
		return this.totalLoanAmount;
	}

	public void setTotalLoanAmount(Double totalLoanAmount) {
		this.totalLoanAmount = totalLoanAmount;
	}

}
