package buku.entities;

// Generated Mar 22, 2014 2:39:02 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Transaction generated by hbm2java
 */
public class Transaction implements java.io.Serializable {

	private Integer id;
	private Currency currency;
	private User userByToUserId;
	private User userByFromUserId;
	private Double paidAmount;
	private Date transactionDate;
	private String reason;
	private String photo;
	private Integer transactionType; 

	public Transaction() {
	}

	public Transaction(Currency currency, User userByToUserId,
			User userByFromUserId, Double paidAmount, Date transactionDate) {
		this.currency = currency;
		this.userByToUserId = userByToUserId;
		this.userByFromUserId = userByFromUserId;
		this.paidAmount = paidAmount;
		this.transactionDate = transactionDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Currency getCurrency() {
		return this.currency;
	}

	public void setCurrency(Currency currency) {
		this.currency = currency;
	}

	public User getUserByToUserId() {
		return this.userByToUserId;
	}

	public void setUserByToUserId(User userByToUserId) {
		this.userByToUserId = userByToUserId;
	}

	public User getUserByFromUserId() {
		return this.userByFromUserId;
	}

	public void setUserByFromUserId(User userByFromUserId) {
		this.userByFromUserId = userByFromUserId;
	}

	public Double getPaidAmount() {
		return this.paidAmount;
	}

	public void setPaidAmount(Double paidAmount) {
		this.paidAmount = paidAmount;
	}

	public Date getTransactionDate() {
		return this.transactionDate;
	}

	public void setTransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	public String getReason() {
		return reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public String getPhoto() {
		return photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public Integer getTransactionType() {
		return transactionType;
	}

	public void setTransactionType(Integer transactionType) {
		this.transactionType = transactionType;
	}
	
	
	
	

}
